# Site settings
title: dealertrack.github.io | dealertrack technologies
email: gregory.armer@dealertrack.com
description: > # this means to ignore newlines until "baseurl:"
  Established in 2001, Dealertrack and its web-based software solutions
  and services enhance efficiency and profitability for all major
  segments of the automotive retail industry, including dealers,
  lenders, OEMs, third-party retailers, agents, and aftermarket
  providers.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://dealertrack.github.io" # the base hostname & protocol for your site
twitter_username: DT_Careers
github_username:  dealertrack

# Build settings
markdown: kramdown
